services:
  postgres:
    restart: always
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - nms-net
  tb-core:
    restart: always
    image: "thingsboard/tb-node:4.0.1.1"
    ports:
      - "8080:8080"
      - "7070:7070"
      - "1883:1883"
      - "5683-5688:5683-5688/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    environment:
      TB_SERVICE_ID: tb-core
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - nms-net
  tb-gateway:
    image: "thingsboard/tb-gateway:3.7-stable"
    restart: always
    ports:
      - "5000:5000"
    extra_hosts:
      -  "host.docker.internal:host-gateway"
    environment:
      - host=10.10.10.151
      - port=1883
      - accessToken=${GW_ACCESS_TOKEN}
    volumes:
      - ./tb-gateway/config:/thingsboard_gateway/config
      - ./tb-gateway/connectors:/thingsboard_gateway/connectors
      - ./tb-gateway/extensions:/thingsboard_gateway/extensions
    networks:
      - nms-net
  routeros:
    container_name: "mikrotik"
    image: cnsoluciones/mikrotik:7.6
    privileged: true
    ports:
      - "21:21" #ftp
    # - "22:22" #ssh
      - "23:23" #telnet
      - "80:80" #www
      - "443:443" #www-ssl
      - "1194:1194" #OVPN
      - "1450:1450" #L2TP
      - "8291:8291" #winbox
      - "8728:8728" #api
      - "8729:8729" #api-ssl
      - "13231:13231" #WireGuard
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - nms-net

networks:
  nms-net:
    driver: bridge
